services:

  nginx:
    container_name: ppdb-proxy
    image: nginx:1.25.3-alpine
    ports:
      - 8080:80
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - ppdb

  php:
    container_name: ppdb-app
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - ppdb

  db:
    container_name: ppdb-db
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadbdata:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - ppdb

volumes:
  mariadbdata:

networks:
  ppdb: